<a href="https://colab.research.google.com/github/Khushbuweshval/Khushbu-repo.-1/blob/main/np_pd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy

In [ ]:
import numpy as np #np is an alias of numpy

In [ ]:
My_list=[2,3,7,9,8]

In [ ]:
type(My_list)

list

In [ ]:
#converting a list into an array
arr=np.array(My_list)

In [ ]:
print(arr)

[2 3 7 9 8]

In [ ]:
type(arr)#one dimentional array- 1 dimentional array

numpy.ndarray

In [ ]:
arr.shape

(5,)

In [ ]:
#2-dimentional array -Multinested array
My_list_1=[2,3,7,9,8]
My_list_2=[2,3,4,1,7]
My_list_3=[9,8,0,4,5]

arr_new=np.array([My_list_1,My_list_2,My_list_3])

In [ ]:
print(arr_new)

[[2 3 7 9 8]
 [2 3 4 1 7]
 [9 8 0 4 5]]

In [ ]:
arr_new.shape #3 is row,5 is calumns

(3, 5)

In [ ]:
arr_new.reshape(5,3)#Transpose of matrix (converting rows into columns, columns)

array([[2, 3, 7],
       [9, 8, 2],
       [3, 4, 1],
       [7, 9, 8],
       [0, 4, 5]])

Creat a numpy matrix of shape( 2,4)

In [ ]:
arr_1=[2,3,1,4]
arr_2=[9,5,6,0]

In [ ]:
new_arr=np.array([arr_1,arr_2])

In [ ]:
new_arr

array([[2, 3, 1, 4],
       [9, 5, 6, 0]])

In [ ]:
new_arr.reshape(4,2)

array([[2, 3],
       [1, 4],
       [9, 5],
       [6, 0]])

Numerical analysis

In [ ]:
a=np.array([2,3,5,6,8])
print('adding 1 to each number from the list',a+1)
print("subtract 1 from each number from the list",a-1)
print("multiply 5 to each element from the list",a*5)
print("square of each element from the list",a**2)

adding 1 to each number from the list [3 4 6 7 9]
subtract 1 from each number from the list [1 2 4 5 7]
multiply 5 to each element from the list [10 15 25 30 40]
square of each element from the list [ 4  9 25 36 64]

In [ ]:
print(a+1)
print(a-1)
print(a*5)
print(a**2)

[3 4 6 7 9]
[1 2 4 5 7]
[10 15 25 30 40]
[ 4  9 25 36 64]

generating random numbers

In [ ]:
np.arange(1,20,1)#from 1 to 20 we will have equal spaced numbers (step size is 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
np.arange(1,20,3)#each number will have equal difference of 3

array([ 1,  4,  7, 10, 13, 16, 19])

In [ ]:
np.linspace(1,10,50)#here 50 is the no of elements we need between 1to10

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27272727,
        7.36363636,  7.45454545,  7.54545455,  7.63636364,  7.72727273,
        7.81818182,  7.90909091,  8.        ,  8.09090909,  8.18181818,
        8.27272727,  8.36363636,  8.45454545,  8.54545455,  8.63636364,
        8.72727273,  8.81818182,  8.90909091,  9.        ,  9.09090909,
        9.18181818,  9.27272727,  9.36363636,  9.45454545,  9.54545455,
        9.63636364,  9.72727273,  9.81818182,  9.90909091, 10.        ])

In [ ]:
#generating a random float number between 0 and 1(here 1 is exclusive)
num=np.random.rand()

In [ ]:
print(num)

0.7386941667232105

In [ ]:
int_num=np.random.randint(1,10)

In [ ]:
print(int_num)

2

In [ ]:
np.random.rand(3,4)#here 3 meansa numbers of row and 4 means the number of colums

array([[0.08798388, 0.51776539, 0.73233119, 0.96835518],
       [0.25262176, 0.59850434, 0.91055397, 0.59086803],
       [0.67969393, 0.16303654, 0.22820857, 0.89307206]])

Pandas

In [ ]:
import pandas as pd #pd is alias of pandas

In [ ]:
data=pd.read_csv("/content/tips.csv")

In [ ]:
data.head()#head() will display the first 5 rows of your dataset

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
data.head(15)#this time we are able to see first 15 rows of your dataset

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2

In [ ]:
data.tail()#tail will display the last 5 rows

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
data.tail(10)#last 10 rows

     total_bill   tip     sex smoker   day    time  size
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
data.info()#info() help in doing basic analysis

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [ ]:
data.describe() #describe() help in doing statistical analysis

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
#dummy dataset

In [ ]:
My_data=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['row0','row1','row2','row3','row4'],columns=['col0','col1','col2','col3'])

In [ ]:
print(My_data)

      col0  col1  col2  col3
row0     0     1     2     3
row1     4     5     6     7
row2     8     9    10    11
row3    12    13    14    15
row4    16    17    18    19

In [ ]:
My_data.iloc[2:4,2:]

      col2  col3
row2    10    11
row3    14    15

In [ ]:
My_data.iloc[2:4,0:3]

      col0  col1  col2
row2     8     9    10
row3    12    13    14